name: ActionCommitCheck.CI

on: [pull-request, push]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
      steps:
        - name: Check Commit Email
          uses: 
